---
- name: Install Git on All Servers
  hosts: servers
  become: yes

  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

- name: Install Git on Group 1
  hosts: group1
  become: yes

  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

- name: Install Git on Group 2
  hosts: group2
  become: yes

  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present
